#!/bin/bash
# ~/.bash_logout
clear
echo "        ##                      #"
echo "        ##                      #"
echo "        #########################"
echo "        #########################"
echo "        ##            #         #"
echo "        ##            #         #"
echo "        ##            #         #"
echo "        ##           ##        ##"
echo "         ##         ####      ## "
echo "         ####      ### #########"
echo "          ###########   ###### "
echo "            #######"
echo "  #                   #"
echo " ###                ###"
echo " ##             #######"
echo "    ###     ######### #"
echo "        #########"
echo "           ### "
echo "               ####"
echo "                   ####"
echo "                      #"
echo "             #####"
echo "           ######### "
echo "         ####  #   ###"
echo "         #     #     ##"
echo "        ##     #      #"
echo "         #     #     ##"
echo "         #     #   ###"
echo "           #   ##### "
echo ""
